// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu0Ug9EWfxX5qkz-oavfo2lvVyi3x6P5M',
    appId: '1:818296297777:web:54803648ed1639c8347810',
    messagingSenderId: '818296297777',
    projectId: 'skincancer2-fd2bf',
    authDomain: 'skincancer2-fd2bf.firebaseapp.com',
    storageBucket: 'skincancer2-fd2bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBNUlOrFHLtjR9BLqJO2bRHJGRFnjt9VQ',
    appId: '1:818296297777:android:af2812310e44ef59347810',
    messagingSenderId: '818296297777',
    projectId: 'skincancer2-fd2bf',
    storageBucket: 'skincancer2-fd2bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmlbtxeSKMgk1qb3646WVYwQMAI1RvpT8',
    appId: '1:818296297777:ios:dce30151e01b3f05347810',
    messagingSenderId: '818296297777',
    projectId: 'skincancer2-fd2bf',
    storageBucket: 'skincancer2-fd2bf.firebasestorage.app',
    iosBundleId: 'com.example.skinCancerDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmlbtxeSKMgk1qb3646WVYwQMAI1RvpT8',
    appId: '1:818296297777:ios:dce30151e01b3f05347810',
    messagingSenderId: '818296297777',
    projectId: 'skincancer2-fd2bf',
    storageBucket: 'skincancer2-fd2bf.firebasestorage.app',
    iosBundleId: 'com.example.skinCancerDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu0Ug9EWfxX5qkz-oavfo2lvVyi3x6P5M',
    appId: '1:818296297777:web:0feeaa7dcdfc020f347810',
    messagingSenderId: '818296297777',
    projectId: 'skincancer2-fd2bf',
    authDomain: 'skincancer2-fd2bf.firebaseapp.com',
    storageBucket: 'skincancer2-fd2bf.firebasestorage.app',
  );
}
